### ISSUE TITLE
ACE editor does not align the cursor on Safari

### ISSUE THREAD

**Issue by yushan87** [ClemsonRSRG/beginToReason#5]
Not sure what is causing the issue, but the cursor does not reflect your current position in the file.

**Comment by timschwab** [comment]
This is occurring because Safari's fixed width font is screwy. ACE assumes that every character in the font has the same width in pixels, but in Safari a bold letter is very slightly wider. The theme that we are using has some bold in it, so we could change it. But we are keeping the theme for two reasons. One, all the students use Firefox in lab, and Safari or Ace might update to fix this bug themselves.

**Comment by timschwab** [comment]
This is caused by line 25 of /create/javascript/inject.js
